spring.application.name=SemanticKernal
openai.api.key=
ollama.model=llama3.2:latest
ollama.base-url=http://my:11434/v1

logging.level.com.azure.core.http=DEBUG
logging.level.com.azure.core.http.netty=DEBUG
